# description
description = "The unit was formed from Turkic-speaking ethnic groups from the Caucasus, Central Asia and the Russian Federation, as well as Chinese Uighurs. The battalion is headed by a refugee from Kyrgyzstan, Almaz Kudabek."
# socials
facebook = ""
telegram = ""
youtube = ""
twitter = ""